# Generated by Django 4.2.26 on 2025-11-20 15:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', help_text="Rôle de l'utilisateur", max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS latitude', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS longitude', max_digits=9, null=True, verbose_name='Longitude')),
                ('active', models.BooleanField(db_index=True, default=True, help_text="Si désactivé, n'apparaît pas dans les API publiques", verbose_name='Actif')),
                ('details', models.TextField(blank=True, help_text="Informations complémentaires sur l'agence", null=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agencies', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=500, verbose_name='Description courte')),
                ('detailed_description', models.TextField(verbose_name='Description détaillée')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image')),
                ('active', models.BooleanField(db_index=True, default=True, help_text="Si désactivé, n'apparaît pas dans les API publiques", verbose_name='Actif')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['active', 'order'], name='api_service_active_4dafd2_idx'), models.Index(fields=['slug'], name='api_service_slug_142ea7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Identifiant unique (ex: home_banner, about_text)', max_length=100, unique=True, verbose_name='Clé')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre')),
                ('body', models.TextField(help_text='Contenu HTML ou texte', verbose_name='Contenu')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Si désactivé, n'apparaît pas dans les API publiques", verbose_name='Actif')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Contenu de page',
                'verbose_name_plural': 'Contenus de pages',
                'ordering': ['order', 'key'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='api_pagecon_is_acti_a51e7a_idx'), models.Index(fields=['key'], name='api_pagecon_key_8c4cd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('role', models.CharField(blank=True, help_text='Titre du poste (ex: Directeur, Responsable)', max_length=200, null=True, verbose_name='Rôle / Poste')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_headquarter', models.BooleanField(db_index=True, default=False, help_text='Contact du siège social (ex: Paris)', verbose_name='Siège social')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, help_text='Agence associée (vide si siège)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='api.agency', verbose_name='Agence')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-is_headquarter', 'name'],
                'indexes': [models.Index(fields=['is_headquarter'], name='api_contact_is_head_6e6473_idx'), models.Index(fields=['agency'], name='api_contact_agency__15b3df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['active'], name='api_agency_active_74d292_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['slug'], name='api_agency_slug_073045_idx'),
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['latitude', 'longitude'], name='api_agency_latitud_b66b29_idx'),
        ),
    ]
