# Generated by Django 4.2.26 on 2025-11-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, help_text="Ex: '2-4 heures', '1 journée', etc.", max_length=100, null=True, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Liste des caractéristiques avec checkmarks (format JSON)', verbose_name='Caractéristiques'),
        ),
        migrations.AddField(
            model_name='service',
            name='guarantees',
            field=models.JSONField(blank=True, default=list, help_text='Liste des garanties (format JSON)', verbose_name='Garanties'),
        ),
        migrations.AddField(
            model_name='service',
            name='included_services',
            field=models.JSONField(blank=True, default=list, help_text='Liste des prestations incluses (format JSON)', verbose_name='Prestations incluses'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_label',
            field=models.CharField(blank=True, help_text="Ex: 'À partir de 25€/heure'", max_length=200, null=True, verbose_name='Label du prix'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix en euros par heure', max_digits=10, null=True, verbose_name='Prix par heure (€)'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list, help_text="Liste des étapes du processus (format JSON: [{'step': 1, 'title': '...', 'description': '...'}, ...])", verbose_name='Étapes du processus'),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Note sur 5 (ex: 4.8)', max_digits=3, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.IntegerField(default=0, help_text="Nombre total d'avis clients", verbose_name="Nombre d'avis"),
        ),
    ]
