# Generated by Django 4.2.26 on 2025-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_duration_service_features_service_guarantees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text="Catégorie du service (ex: 'Garde d'enfants', 'Ménage et repassage', 'Jardinage', etc.)", max_length=100, null=True, verbose_name='Catégorie'),
        ),
    ]
