# Generated by Django 4.2.26 on 2025-11-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('show_in_navbar', models.BooleanField(default=True, help_text='Si coché, cette catégorie apparaîtra dans le menu de navigation', verbose_name='Afficher dans la navbar')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Catégorie du service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='api.category', verbose_name='Catégorie'),
        ),
    ]
