# Generated by Django 4.2.26 on 2025-11-20 20:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_alter_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(help_text='Commentaire du client', verbose_name='Commentaire')),
                ('client_name', models.CharField(help_text='Nom affiché (peut être anonyme)', max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('approved', models.BooleanField(db_index=True, default=False, help_text="L'avis doit être approuvé par un admin avant d'être affiché", verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.service', verbose_name='Service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'approved'], name='api_service_service_f21329_idx'), models.Index(fields=['approved', '-created_at'], name='api_service_approve_f375b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(db_index=True, default=True, help_text="Si désactivé, n'apparaît pas sur le site", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['order', 'question'],
                'indexes': [models.Index(fields=['service', 'active', 'order'], name='api_service_service_7f0957_idx')],
            },
        ),
    ]
