# Generated by Django 4.2.26 on 2025-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_servicereview_servicefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone spécifique pour ce service (optionnel)', max_length=20, null=True, verbose_name='Numéro de contact'),
        ),
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('FCFA', 'Franc CFA (FCFA)')], default='EUR', help_text="Devise pour l'affichage des prix", max_length=10, verbose_name='Devise'),
        ),
    ]
