# Generated by Django 4.2.26 on 2025-11-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_service_contact_phone_service_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_faq',
            field=models.BooleanField(default=True, help_text='Si désactivé, la section FAQ ne sera pas affichée sur la page de détail', verbose_name='Afficher les FAQ'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_reviews',
            field=models.BooleanField(default=True, help_text='Si désactivé, la section avis ne sera pas affichée sur la page de détail', verbose_name='Afficher les avis'),
        ),
    ]
