# Generated by Django 4.2.26 on 2025-11-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_service_show_faq_service_show_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='display_on_page',
            field=models.BooleanField(db_index=True, default=True, help_text="Si désactivé, l'avis ne sera pas affiché sur la page de détail même s'il est approuvé", verbose_name='Afficher sur la page'),
        ),
    ]
