# Generated by Django 4.2.26 on 2025-11-20 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_servicereview_display_on_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Adresse complète du client', max_length=500, verbose_name='Localisation')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Informations dynamiques collectées dans le formulaire', verbose_name='Informations supplémentaires')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONTACTED', 'Contacté'), ('QUOTED', 'Devis envoyé'), ('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé'), ('COMPLETED', 'Terminé')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes internes pour le suivi', null=True, verbose_name='Notes admin')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de contact')),
                ('quoted_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi du devis")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur créateur')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='api.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Demande de devis',
                'verbose_name_plural': 'Demandes de devis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_quotere_status_6fe288_idx'), models.Index(fields=['service', 'status'], name='api_quotere_service_4dad92_idx')],
            },
        ),
    ]
