# Generated by Django 4.2.26 on 2025-11-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_quoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'avantage (ex: Professionnels certifiés)", max_length=200, verbose_name='Titre')),
                ('description', models.TextField(help_text="Description de l'avantage", verbose_name='Description')),
                ('icon', models.CharField(choices=[('FaUsers', 'Utilisateurs'), ('FaShieldAlt', 'Bouclier'), ('FaClock', 'Horloge'), ('FaCheckCircle', 'Coche'), ('FaStar', 'Étoile'), ('FaAward', 'Récompense'), ('FaMapMarkerAlt', 'Localisation'), ('FaPhone', 'Téléphone'), ('FaEnvelope', 'Email'), ('FaHeart', 'Cœur'), ('FaHandHoldingHeart', 'Main avec cœur'), ('FaUserTie', 'Professionnel')], default='FaUsers', help_text='Icône à afficher pour cet avantage', max_length=50, verbose_name='Icône')),
                ('order', models.IntegerField(db_index=True, default=0, help_text="Ordre d'affichage (plus petit = affiché en premier)", verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(db_index=True, default=True, help_text="Si désactivé, n'apparaît pas sur le site", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avantage service',
                'verbose_name_plural': 'Avantages services',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['active', 'order'], name='api_service_active_559687_idx')],
            },
        ),
    ]
