# Generated by Django 4.2.26 on 2025-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_serviceadvantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de l'agence", null=True, upload_to='agencies/', verbose_name='Image'),
        ),
    ]
