# Generated by Django 4.2.26 on 2025-11-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_agency_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='agencies',
            field=models.ManyToManyField(blank=True, help_text='Agences où ce service est disponible', related_name='services', to='api.agency', verbose_name='Agences'),
        ),
    ]
