# Generated by Django 4.2.26 on 2025-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_service_agencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#DC2626', help_text='Couleur principale du site (format hex: #DC2626)', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#B91C1C', help_text='Couleur secondaire pour les dégradés (format hex: #B91C1C)', max_length=7, verbose_name='Couleur secondaire')),
                ('tertiary_color', models.CharField(default='#991B1B', help_text='Couleur tertiaire pour les effets hover (format hex: #991B1B)', max_length=7, verbose_name='Couleur tertiaire')),
                ('logo', models.ImageField(blank=True, help_text='Logo principal du site', null=True, upload_to='site/', verbose_name='Logo du site')),
                ('logo_favicon', models.ImageField(blank=True, help_text='Icône du site (favicon)', null=True, upload_to='site/', verbose_name='Favicon')),
                ('site_name', models.CharField(default='Services Locaux', help_text='Nom affiché sur le site', max_length=200, verbose_name='Nom du site')),
                ('site_tagline', models.CharField(default='Votre partenaire de confiance', help_text='Slogan ou tagline du site', max_length=500, verbose_name='Slogan du site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
