# Generated by Django 4.2.26 on 2025-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='button_primary_color',
            field=models.CharField(default='#DC2626', help_text='Couleur de fond des boutons principaux (CTA, actions importantes) - Si vide, utilise la couleur principale', max_length=7, verbose_name='Couleur des boutons principaux'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_primary_hover_color',
            field=models.CharField(default='#B91C1C', help_text='Couleur au survol des boutons principaux - Si vide, utilise la couleur secondaire', max_length=7, verbose_name='Couleur hover des boutons principaux'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', help_text="Couleur du texte à l'intérieur des boutons (généralement blanc #FFFFFF)", max_length=7, verbose_name='Couleur du texte des boutons'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_link_color',
            field=models.CharField(default='#DC2626', help_text='Couleur des liens cliquables dans le contenu - Si vide, utilise la couleur principale', max_length=7, verbose_name='Couleur des liens'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_link_hover_color',
            field=models.CharField(default='#B91C1C', help_text='Couleur au survol des liens - Si vide, utilise la couleur secondaire', max_length=7, verbose_name='Couleur hover des liens'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_primary_color',
            field=models.CharField(default='#DC2626', help_text='Couleur utilisée pour les textes importants, titres secondaires et accents (format hex: #DC2626)', max_length=7, verbose_name='Couleur des textes importants'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#DC2626', help_text='Couleur principale utilisée pour les titres, liens importants et éléments de navigation (format hex: #DC2626)', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#B91C1C', help_text='Couleur secondaire utilisée pour les dégradés et effets hover sur les boutons (format hex: #B91C1C)', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tertiary_color',
            field=models.CharField(default='#991B1B', help_text='Couleur tertiaire utilisée pour les effets hover et états actifs (format hex: #991B1B)', max_length=7, verbose_name='Couleur tertiaire'),
        ),
    ]
