# Generated by Django 4.2.26 on 2025-11-28 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sitesettings_button_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Numéro unique de la facture (ex: FACT-2024-001)', max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Montant HT', max_digits=10, verbose_name='Sous-total')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de TVA en pourcentage (ex: 20.00 pour 20%)', max_digits=5, verbose_name='Taux de TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Montant de la TVA', max_digits=10, verbose_name='Montant TVA')),
                ('total', models.DecimalField(decimal_places=2, help_text='Montant total TTC', max_digits=10, verbose_name='Total TTC')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'Dollar ($)'), ('FCFA', 'Franc CFA (FCFA)')], default='EUR', max_length=10, verbose_name='Devise')),
                ('invoice_date', models.DateField(help_text="Date d'émission de la facture", verbose_name='Date de facturation')),
                ('due_date', models.DateField(blank=True, help_text='Date limite de paiement (optionnel)', null=True, verbose_name="Date d'échéance")),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur la facture', null=True, verbose_name='Notes')),
                ('payment_terms', models.TextField(blank=True, help_text='Conditions de paiement (ex: Paiement à 30 jours)', null=True, verbose_name='Conditions de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('quote_request', models.OneToOneField(help_text='Devis associé à cette facture', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.quoterequest', verbose_name='Demande de devis')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='api_invoice_invoice_59a3b3_idx'), models.Index(fields=['quote_request'], name='api_invoice_quote_r_5a66fe_idx'), models.Index(fields=['-invoice_date'], name='api_invoice_invoice_f212df_idx')],
            },
        ),
    ]
