# Generated by Django 4.2.26 on 2025-11-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro unique de la facture (ex: FACT-2024-001)', max_length=50, null=True, unique=True, verbose_name='Numéro de facture'),
        ),
    ]
