# Generated by Django 4.2.26 on 2025-11-28 23:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Prix calculé automatiquement depuis les choix du formulaire', max_digits=10, null=True, verbose_name='Prix calculé'),
        ),
        migrations.CreateModel(
            name='QuoteFormStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('SERVICE_SELECTION', 'Sélection du service'), ('LOCATION', 'Localisation'), ('SINGLE_CHOICE', 'Choix unique'), ('MULTIPLE_CHOICE', 'Choix multiples'), ('TEXT_INPUT', 'Saisie texte'), ('CONTACT', 'Coordonnées de contact')], max_length=50, verbose_name="Type d'étape")),
                ('title', models.CharField(help_text="Ex: 'Quel type d'aide souhaitez-vous ?'", max_length=200, verbose_name="Titre de l'étape")),
                ('description', models.TextField(blank=True, help_text='Description ou instructions pour cette étape', null=True, verbose_name='Description')),
                ('order', models.IntegerField(db_index=True, default=0, help_text="Ordre d'affichage de l'étape", verbose_name='Ordre')),
                ('required', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('field_key', models.CharField(help_text="Clé utilisée pour stocker la réponse (ex: 'typeAide', 'besoins')", max_length=100, verbose_name='Clé du champ')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='Service associé à cette étape', on_delete=django.db.models.deletion.CASCADE, related_name='quote_form_steps', to='api.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Étape du formulaire de devis',
                'verbose_name_plural': 'Étapes des formulaires de devis',
                'ordering': ['service', 'order'],
                'unique_together': {('service', 'field_key')},
            },
        ),
        migrations.CreateModel(
            name='QuoteFormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Texte affiché pour cette option', max_length=200, verbose_name='Libellé')),
                ('value', models.CharField(help_text='Valeur stockée quand cette option est sélectionnée', max_length=200, verbose_name='Valeur')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prix associé à cette option', max_digits=10, verbose_name='Prix (€)')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('allow_custom_text', models.BooleanField(default=False, help_text="Si activé, l'utilisateur peut saisir un texte personnalisé", verbose_name='Permettre texte personnalisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.quoteformstep', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Option du formulaire',
                'verbose_name_plural': 'Options des formulaires',
                'ordering': ['step', 'order'],
            },
        ),
    ]
