# Generated by Django 4.2.26 on 2025-11-29 18:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_quoterequest_calculated_price_quoteformstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteformoption',
            name='price_enabled',
            field=models.BooleanField(default=True, help_text="Si activé, le prix sera ajouté au total. Si désactivé, le prix sera ignoré même s'il est défini.", verbose_name='Prix activé'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Réduction en pourcentage appliquée au montant total', max_digits=5, null=True, verbose_name='Réduction (%)'),
        ),
    ]
