# Generated by Django 4.2.26 on 2025-11-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_quoteformoption_price_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteformoption',
            options={'ordering': ['step', 'parent', 'order'], 'verbose_name': 'Option du formulaire', 'verbose_name_plural': 'Options des formulaires'},
        ),
        migrations.AddField(
            model_name='quoteformoption',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Option parente pour créer une hiérarchie infinie de sous-options', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_options', to='api.quoteformoption', verbose_name='Option parente'),
        ),
    ]
