# Generated by Django 4.2.27 on 2026-02-03 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_quoterequest_service_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('qr_code', models.CharField(db_index=True, help_text='Code QR unique pour le patient', max_length=100, unique=True, verbose_name='QR Code')),
                ('qr_code_image', models.ImageField(blank=True, help_text='Image du QR code générée', null=True, upload_to='qr_codes/', verbose_name='Image QR Code')),
                ('is_active', models.BooleanField(default=True, help_text='Si désactivé, le QR code ne peut plus être scanné', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('DEPART', 'Départ')], help_text='Type de scan (arrivée ou départ)', max_length=10, verbose_name='Statut')),
                ('scan_time', models.DateTimeField(auto_now_add=True, help_text='Date et heure du scan', verbose_name='Heure de scan')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS (optionnel)', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS (optionnel)', max_digits=9, null=True, verbose_name='Longitude')),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles (optionnel)', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='quoteformoption',
            options={'ordering': ['step', 'order', 'id'], 'verbose_name': 'Option du formulaire', 'verbose_name_plural': 'Options des formulaires'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce compte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(blank=True, db_index=True, help_text='Matricule unique pour les employés (utilisé pour la connexion)', max_length=50, null=True, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('EMPLOYE', 'Employé'), ('CLIENT', 'Client')], default='CLIENT', help_text="Rôle de l'utilisateur", max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['matricule'], name='api_customu_matricu_eed217_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='api_customu_role_3dda3d_idx'),
        ),
        migrations.AddField(
            model_name='presence',
            name='employe',
            field=models.ForeignKey(help_text='Employé qui a scanné le QR code', limit_choices_to={'role': 'EMPLOYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL, verbose_name='Employé'),
        ),
        migrations.AddField(
            model_name='presence',
            name='patient',
            field=models.ForeignKey(help_text='Patient pour lequel la présence est enregistrée', on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='api.patient', verbose_name='Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='client',
            field=models.ForeignKey(help_text='Client propriétaire du patient', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(help_text='Admin qui a créé ce patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['patient', 'scan_time'], name='api_presenc_patient_b3d5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['employe', 'scan_time'], name='api_presenc_employe_7d9635_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['status', 'scan_time'], name='api_presenc_status_110670_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['qr_code'], name='api_patient_qr_code_fb2df5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['client', 'is_active'], name='api_patient_client__8752a7_idx'),
        ),
    ]
