# Generated by Django 4.2.27 on 2026-02-03 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_patient_presence_alter_quoteformoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1, null=True, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Photo de profil')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='employees/signatures/', verbose_name='Signature')),
                ('email_professionnel', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email professionnel')),
                ('email_personnel', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email personnel')),
                ('telephone_principal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone principal')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone secondaire')),
                ('adresse_numero_rue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numéro et rue')),
                ('adresse_ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('adresse_code_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal')),
                ('adresse_pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('SUPPRIME', 'Supprimé')], default='ACTIF', max_length=20, verbose_name='Statut du compte')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('tentatives_connexion_echouees', models.IntegerField(default=0, verbose_name='Tentatives de connexion échouées')),
                ('appareil_utilise', models.CharField(blank=True, max_length=200, null=True, verbose_name='Appareil utilisé')),
                ('ip_derniere_connexion', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP dernière connexion')),
                ('poste_fonction', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste / Fonction')),
                ('service_departement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Service / Département')),
                ('type_contrat', models.CharField(blank=True, choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('PRESTATION', 'Contrat de Prestation')], max_length=20, null=True, verbose_name='Type de contrat')),
                ('date_debut_contrat', models.DateField(blank=True, null=True, verbose_name='Date de début du contrat')),
                ('date_fin_contrat', models.DateField(blank=True, null=True, verbose_name='Date de fin du contrat')),
                ('temps_travail', models.CharField(blank=True, choices=[('PLEIN', 'Temps plein'), ('PARTIEL', 'Temps partiel')], max_length=20, null=True, verbose_name='Temps de travail')),
                ('taux_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux horaire')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire')),
                ('mode_paiement', models.CharField(blank=True, choices=[('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('ESPECES', 'Espèces'), ('AUTRE', 'Autre')], max_length=20, null=True, verbose_name='Mode de paiement')),
                ('numero_securite_sociale', models.CharField(blank=True, help_text='Si légalement autorisé', max_length=50, null=True, verbose_name='Numéro de sécurité sociale')),
                ('numero_employe_interne', models.CharField(blank=True, max_length=50, null=True, verbose_name="Numéro d'employé interne")),
                ('contrat_signe', models.FileField(blank=True, null=True, upload_to='employees/contrats/', verbose_name='Contrat signé (PDF)')),
                ('avenants', models.FileField(blank=True, null=True, upload_to='employees/avenants/', verbose_name='Avenants')),
                ('clause_non_concurrence', models.FileField(blank=True, null=True, upload_to='employees/clauses/', verbose_name='Clause de non-concurrence (signée)')),
                ('note_information', models.FileField(blank=True, null=True, upload_to='employees/notes/', verbose_name="Note d'information (signée)")),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='employees/pieces_identite/', verbose_name="Pièce d'identité")),
                ('diplomes_certifications', models.FileField(blank=True, null=True, upload_to='employees/diplomes/', verbose_name='Diplômes / Certifications')),
                ('documents_administratifs', models.FileField(blank=True, null=True, upload_to='employees/documents/', verbose_name='Documents administratifs divers')),
                ('date_signature_electronique', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature électronique')),
                ('statut_documents', models.CharField(choices=[('SIGNE', 'Signé'), ('EN_ATTENTE', 'En attente'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut des documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Utilisateur associé à ce profil employé', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil employé',
                'verbose_name_plural': 'Profils employés',
                'ordering': ['-created_at'],
            },
        ),
    ]
