# Generated by Django 4.2.27 on 2026-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='scan_time',
            field=models.DateTimeField(blank=True, default=None, help_text='Date et heure du scan', null=True, verbose_name='Heure de scan'),
        ),
    ]
