# Generated by Django for section-specific colors (banner button, services, agencies, employe, admin login, employe login)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_sitesettings_slogan_outline_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_button_color',
            field=models.CharField(blank=True, default='', help_text='Fond du bouton dans la bannière (vide = couleur principale)', max_length=7, null=True, verbose_name='Couleur bouton bannière'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_button_border_color',
            field=models.CharField(blank=True, default='', help_text='Bordure du bouton dans la bannière (vide = pas de bordure)', max_length=7, null=True, verbose_name='Bordure bouton bannière'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Fond section Services'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_text_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Texte section Services'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_button_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bouton section Services'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_button_border_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bordure bouton section Services'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agencies_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Fond section Agences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agencies_text_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Texte section Agences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agencies_button_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bouton section Agences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='agencies_button_border_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bordure bouton section Agences'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Fond interface employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_text_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Texte interface employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_button_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bouton interface employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_button_border_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bordure bouton interface employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_login_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Fond page connexion admin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_login_text_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Texte page connexion admin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_login_button_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bouton page connexion admin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_login_button_border_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bordure bouton page connexion admin'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_login_bg_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Fond page connexion employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_login_text_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Texte page connexion employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_login_button_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bouton page connexion employé'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='employe_login_button_border_color',
            field=models.CharField(blank=True, default='', max_length=7, null=True, verbose_name='Bordure bouton page connexion employé'),
        ),
    ]
