# Generated by Django 4.2.28 on 2026-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_patient_client_optional'),
        ('api', '0036_agency_horaires_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='horaires',
            field=models.TextField(blank=True, help_text='Ex. : Lun-Ven 9h-18h, Sam 9h-12h. Texte libre.', null=True, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='agency',
            name='opening_hours',
            field=models.JSONField(blank=True, help_text='Ex. : {"lundi": {"open": true, "start": "09:00", "end": "18:00"}, ...}', null=True, verbose_name="Horaires d'ouverture (structurés)"),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='button_link_type',
            field=models.CharField(blank=True, choices=[('', 'Pas de bouton'), ('devis', 'Devis personnalisé (/devis)'), ('services', 'Services (/services)'), ('agences', 'Agences (/agences)'), ('custom', 'Autre (URL personnalisée)')], default='devis', help_text="Où mène le bouton « J'en profite »", max_length=20, verbose_name='Destination du bouton'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='button_text',
            field=models.CharField(blank=True, default="J'en profite !", max_length=80, verbose_name='Texte du bouton'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='button_url',
            field=models.CharField(blank=True, help_text='Utilisé uniquement si destination = Autre', max_length=500, null=True, verbose_name='URL personnalisée'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='banner_bg_color',
            field=models.CharField(blank=True, default='#087A00', help_text='Fond du bandeau promotionnel (client, admin, employé)', max_length=7, null=True, verbose_name='Couleur de fond de la bannière'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_border_color',
            field=models.CharField(blank=True, default='', help_text='Bordure des boutons principaux (vide = pas de bordure)', max_length=7, null=True, verbose_name='Couleur de la bordure des boutons'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_outline_border_color',
            field=models.CharField(blank=True, default='#087A00', help_text='Bordure des boutons type Connexion', max_length=7, null=True, verbose_name='Couleur bordure boutons outline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_outline_hover_bg_color',
            field=models.CharField(blank=True, default='#087A00', help_text='Fond au survol des boutons type Connexion', max_length=7, null=True, verbose_name='Couleur fond hover boutons outline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_outline_text_color',
            field=models.CharField(blank=True, default='#087A00', help_text='Texte des boutons type Connexion', max_length=7, null=True, verbose_name='Couleur texte boutons outline'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_primary_color',
            field=models.CharField(default='#087A00', help_text='Couleur de fond des boutons principaux (CTA, actions importantes) - Si vide, utilise la couleur principale', max_length=7, verbose_name='Couleur des boutons principaux'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='button_primary_hover_color',
            field=models.CharField(default='#066300', help_text='Couleur au survol des boutons principaux - Si vide, utilise la couleur secondaire', max_length=7, verbose_name='Couleur hover des boutons principaux'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_bg_color',
            field=models.CharField(blank=True, default='#F0FDF4', help_text='Fond du pied de page (client, admin, employé)', max_length=7, null=True, verbose_name='Couleur de fond du footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_border_color',
            field=models.CharField(blank=True, default='#BBF7D0', help_text='Bordures et séparateurs du footer', max_length=7, null=True, verbose_name='Couleur des bordures du footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_link_color',
            field=models.CharField(blank=True, default='#087A00', help_text='Liens et icônes du footer', max_length=7, null=True, verbose_name='Couleur des liens du footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_link_hover_color',
            field=models.CharField(blank=True, default='#066300', help_text='Au survol des liens du footer', max_length=7, null=True, verbose_name='Couleur hover des liens du footer'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#087A00', help_text='Couleur principale (format hex, ex: #087A00)', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#066300', help_text='Couleur secondaire pour dégradés et hover (format hex, ex: #066300)', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_part2_color',
            field=models.CharField(blank=True, default='#087A00', help_text='Deuxième partie du nom (ex. Locaux)', max_length=7, null=True, verbose_name='Couleur 2 du nom (slogan)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tertiary_color',
            field=models.CharField(default='#044000', help_text='Couleur tertiaire pour hover et états actifs (format hex, ex: #044000)', max_length=7, verbose_name='Couleur tertiaire'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_link_color',
            field=models.CharField(default='#087A00', help_text='Couleur des liens cliquables dans le contenu - Si vide, utilise la couleur principale', max_length=7, verbose_name='Couleur des liens'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_link_hover_color',
            field=models.CharField(default='#066300', help_text='Couleur au survol des liens - Si vide, utilise la couleur secondaire', max_length=7, verbose_name='Couleur hover des liens'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='text_primary_color',
            field=models.CharField(default='#087A00', help_text='Couleur des textes importants et accents (format hex, ex: #087A00)', max_length=7, verbose_name='Couleur des textes importants'),
        ),
    ]
