# Generated by Django 4.2.28 on 2026-03-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône (ex: FaBroom, FaBaby). Vide = auto selon le nom du service.", max_length=50, null=True, verbose_name='Icône'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_icon',
            field=models.BooleanField(default=True, help_text="Si désactivé, l'icône ne sera pas affichée sur les pages publiques", verbose_name="Afficher l'icône"),
        ),
        migrations.AddField(
            model_name='service',
            name='show_pricing',
            field=models.BooleanField(default=True, help_text='Si désactivé, le prix et la durée ne seront pas affichés sur les pages publiques', verbose_name='Afficher la tarification'),
        ),
    ]
