# Generated by Django 4.2.28 on 2026-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_herocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Description courte'),
        ),
    ]
