# Generated by Django 4.2.28 on 2026-03-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_short_description_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(max_length=500, verbose_name='Description courte'),
        ),
    ]
