# Generated by Django 4.2.28 on 2026-03-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_herocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date de naissance du bénéficiaire', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='civility',
            field=models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('', 'Non précisé')], default='', help_text='Civilité du client (Monsieur, Madame)', max_length=10, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Lier ce devis à un patient existant (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='api.patient', verbose_name='Patient / Client enregistré'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='code_ape',
            field=models.CharField(blank=True, help_text="Code APE/NAF de l'entreprise", max_length=10, null=True, verbose_name='Code APE'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='forme_juridique',
            field=models.CharField(blank=True, help_text='Ex: S.A.S., SARL, Auto-entrepreneur...', max_length=50, null=True, verbose_name='Forme juridique'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_secondary',
            field=models.ImageField(blank=True, help_text='Logo partenaire affiché en haut à droite du devis (ex: SI Services à la Personne)', null=True, upload_to='site/', verbose_name='Logo secondaire (partenaire)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mention_bon_pour_accord',
            field=models.TextField(blank=True, default='Si accord, le devis suivant devra être retourné signer avec la mention « Bon pour accord » et constituera une annexe au contrat signé ultérieurement.', help_text="Texte de la mention 'Bon pour accord' en bas du devis", null=True, verbose_name='Mention Bon pour accord'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mention_tva',
            field=models.TextField(blank=True, default="TVA non applicable selon l'article 293 B du Code Général des Impôts", help_text='Mention légale TVA à afficher en bas du devis', null=True, verbose_name='Mention TVA'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='num_tva',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='N° TVA intracommunautaire'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rcs_ville',
            field=models.CharField(blank=True, help_text='Ex: R.C.S. Nanterre', max_length=100, null=True, verbose_name='RCS / Ville'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='siret',
            field=models.CharField(blank=True, help_text="Numéro SIRET de l'entreprise", max_length=50, null=True, verbose_name='SIRET'),
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'A) Sans prise en charge'), ('B', 'B) Avec prise en charge'), ('TOTAL', 'Total'), ('FOOTER', 'Pied de tableau')], default='A', max_length=10, verbose_name='Catégorie')),
                ('label', models.CharField(max_length=300, verbose_name='Libellé de la prestation')),
                ('notes', models.CharField(blank=True, default='', help_text='Ex: tous les jours sauf Dimanche, bonification 25%...', max_length=300, verbose_name='Notes / précisions')),
                ('hours', models.CharField(blank=True, default='', help_text='Ex: 52 heures/mois, Soit (2 heures / J), /', max_length=100, verbose_name="Nombre d'heures")),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tarif horaire (€)')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total (€)')),
                ('total_display', models.CharField(blank=True, default='', help_text="Si rempli, remplace le total calculé dans l'affichage (ex: /, 00,00€)", max_length=100, verbose_name='Affichage total personnalisé')),
                ('is_bold', models.BooleanField(default=False, verbose_name='Ligne en gras')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.quoterequest', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Ligne de devis',
                'verbose_name_plural': 'Lignes de devis',
                'ordering': ['order'],
            },
        ),
    ]
