# Generated by Django 4.2.29 on 2026-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_quoteline_civility_birthdate_sitesettings_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='civility',
            field=models.CharField(blank=True, choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('', 'Non précisé')], default='', max_length=10, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
