# Generated by Django 4.2.29 on 2026-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_patient_civility_birthdate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='hourly_rate_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tarif horaire indiqué par le client', max_digits=6, null=True, verbose_name='Tarif horaire souhaité (€)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='hours_per_month',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Nombre d'heures par mois indiqué par le client", max_digits=6, null=True, verbose_name="Nombre d'heures souhaitées / mois"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paiement_banque',
            field=models.CharField(blank=True, default='LCL', max_length=100, null=True, verbose_name='Banque bénéficiaire'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paiement_beneficiaire',
            field=models.CharField(blank=True, default='EASE-DOM', max_length=100, null=True, verbose_name='Nom du bénéficiaire (paiement)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paiement_bic',
            field=models.CharField(blank=True, default='CRLYFRPP', max_length=20, null=True, verbose_name='Code BIC'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paiement_iban',
            field=models.CharField(blank=True, default='FR38 3000 2005 1000 0000 9774 Z35', max_length=50, null=True, verbose_name='IBAN'),
        ),
    ]
