# Generated by Django 4.2.29 on 2026-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_payment_info_quote_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_signature',
            field=models.ImageField(blank=True, help_text='Image affichée en bas du devis PDF (signature, cachet, logo officiel...)', null=True, upload_to='site/', verbose_name='Signature / Logo de fin de devis'),
        ),
    ]
