# Generated by Django 4.2.29 on 2026-03-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('UNPAID', 'Impayée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EMAIL', 'Email envoyé'), ('PDF', 'PDF généré'), ('OTHER', 'Autre')], max_length=20, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID objet')),
                ('object_repr', models.CharField(blank=True, max_length=300, verbose_name='Représentation')),
                ('detail', models.TextField(blank=True, verbose_name='Détail')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activités",
                'ordering': ['-created_at'],
            },
        ),
    ]
