# Generated by Django 4.2.29 on 2026-03-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='extra',
            field=models.JSONField(blank=True, null=True, verbose_name='Données extra'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=10, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='logger_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logger'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('EMAIL', 'Email envoyé'), ('PDF', 'PDF généré'), ('ERROR', 'Erreur'), ('OTHER', 'Autre')], max_length=20, verbose_name='Action'),
        ),
    ]
