# Generated by Django 4.2.29 on 2026-03-22 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_activitylog_level_logger'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('devis', 'Devis'), ('factures', 'Factures'), ('employes', 'Employés'), ('patients', 'Patients'), ('scans', 'Scans'), ('services', 'Services'), ('categories', 'Catégories'), ('avantages', 'Avantages'), ('agences', 'Agences'), ('avis', 'Avis clients'), ('messages', 'Messages contact'), ('bannieres', 'Bannières'), ('hero', "Page d'accueil"), ('parametres', 'Paramètres')], max_length=50, verbose_name='Module')),
                ('action', models.CharField(choices=[('view', 'Voir'), ('create', 'Créer'), ('update', 'Modifier'), ('delete', 'Supprimer'), ('email', 'Envoyer email'), ('pdf', 'Générer PDF')], max_length=20, verbose_name='Action')),
                ('granted', models.BooleanField(default=False, verbose_name='Accordé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateurs',
                'ordering': ['user', 'module', 'action'],
                'unique_together': {('user', 'module', 'action')},
            },
        ),
    ]
