# Generated by Django 4.2.29 on 2026-03-22 20:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='taux_prise_en_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="Pourcentage pris en charge par l'entreprise sur la partie B", max_digits=5, null=True, verbose_name='Taux prise en charge (%)'),
        ),
    ]
