# Generated by Django 4.2.29 on 2026-03-22 20:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_quote_taux_prise_en_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='remise_partie_a',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Remise en pourcentage accordée sur la partie A', max_digits=5, null=True, verbose_name='Remise Partie A (%)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='remise_partie_a_commentaire',
            field=models.CharField(blank=True, help_text="Ex: Fête de fin d'année, offre spéciale...", max_length=255, null=True, verbose_name='Motif de la remise Partie A'),
        ),
    ]
