# Generated by Django 4.2.29 on 2026-04-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_quote_remise_partie_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_name_libre',
            field=models.CharField(blank=True, help_text='Nom du client si pas de devis ni patient', max_length=200, null=True, verbose_name='Nom client (libre)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient directement associé (si pas de devis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='api.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quote_request',
            field=models.OneToOneField(blank=True, help_text='Devis associé à cette facture (optionnel)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.quoterequest', verbose_name='Demande de devis'),
        ),
    ]
