--
-- PostgreSQL database dump
--

\restrict MwzFg0gq1yReWnDI8qbnp1InCe6dLOhg4UuOXOpaa05h6qbogQsIN2iWxWM5iN1

-- Dumped from database version 15.16
-- Dumped by pg_dump version 15.16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_agency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_agency (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    address text NOT NULL,
    city character varying(100) NOT NULL,
    postal_code character varying(20),
    phone character varying(20),
    email character varying(254),
    latitude numeric(9,6),
    longitude numeric(9,6),
    active boolean NOT NULL,
    details text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    image character varying(100),
    horaires text,
    opening_hours jsonb
);


ALTER TABLE public.api_agency OWNER TO postgres;

--
-- Name: api_agency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    show_in_navbar boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.api_category OWNER TO postgres;

--
-- Name: api_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_contact; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_contact (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    role character varying(200),
    phone character varying(20),
    email character varying(254),
    is_headquarter boolean NOT NULL,
    address text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    agency_id bigint,
    created_by_id bigint
);


ALTER TABLE public.api_contact OWNER TO postgres;

--
-- Name: api_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    phone character varying(20),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    matricule character varying(50)
);


ALTER TABLE public.api_customuser OWNER TO postgres;

--
-- Name: api_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.api_customuser_groups OWNER TO postgres;

--
-- Name: api_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.api_customuser_user_permissions OWNER TO postgres;

--
-- Name: api_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_employeeprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_employeeprofile (
    id bigint NOT NULL,
    sexe character varying(1),
    date_naissance date,
    nationalite character varying(100),
    photo_profil character varying(100),
    signature character varying(100),
    email_professionnel character varying(254),
    email_personnel character varying(254),
    telephone_principal character varying(20),
    telephone_secondaire character varying(20),
    adresse_numero_rue character varying(200),
    adresse_ville character varying(100),
    adresse_code_postal character varying(20),
    adresse_pays character varying(100),
    statut_compte character varying(20) NOT NULL,
    derniere_connexion timestamp with time zone,
    tentatives_connexion_echouees integer NOT NULL,
    appareil_utilise character varying(200),
    ip_derniere_connexion inet,
    poste_fonction character varying(200),
    service_departement character varying(200),
    type_contrat character varying(20),
    date_debut_contrat date,
    date_fin_contrat date,
    temps_travail character varying(20),
    taux_horaire numeric(10,2),
    salaire numeric(10,2),
    mode_paiement character varying(20),
    numero_securite_sociale character varying(50),
    numero_employe_interne character varying(50),
    contrat_signe character varying(100),
    avenants character varying(100),
    clause_non_concurrence character varying(100),
    note_information character varying(100),
    piece_identite character varying(100),
    diplomes_certifications character varying(100),
    documents_administratifs character varying(100),
    date_signature_electronique timestamp with time zone,
    statut_documents character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.api_employeeprofile OWNER TO postgres;

--
-- Name: api_employeeprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_employeeprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_employeeprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_invoice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_invoice (
    id bigint NOT NULL,
    invoice_number character varying(50),
    subtotal numeric(10,2) NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    tax_amount numeric(10,2) NOT NULL,
    total numeric(10,2) NOT NULL,
    currency character varying(10) NOT NULL,
    invoice_date date NOT NULL,
    due_date date,
    notes text,
    payment_terms text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    quote_request_id bigint NOT NULL
);


ALTER TABLE public.api_invoice OWNER TO postgres;

--
-- Name: api_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_pagecontent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_pagecontent (
    id bigint NOT NULL,
    key character varying(100) NOT NULL,
    title character varying(200),
    body text NOT NULL,
    is_active boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    button_link_type character varying(20) NOT NULL,
    button_text character varying(80) NOT NULL,
    button_url character varying(500)
);


ALTER TABLE public.api_pagecontent OWNER TO postgres;

--
-- Name: api_pagecontent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_pagecontent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_pagecontent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_patient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_patient (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    phone character varying(20),
    address text,
    qr_code character varying(100) NOT NULL,
    qr_code_image character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    client_id bigint NOT NULL,
    created_by_id bigint
);


ALTER TABLE public.api_patient OWNER TO postgres;

--
-- Name: api_patient_assigned_employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_patient_assigned_employees (
    id bigint NOT NULL,
    patient_id bigint NOT NULL,
    customuser_id bigint NOT NULL
);


ALTER TABLE public.api_patient_assigned_employees OWNER TO postgres;

--
-- Name: api_patient_assigned_employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_patient_assigned_employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_patient_assigned_employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_patient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_patient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_presence; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_presence (
    id bigint NOT NULL,
    status character varying(10) NOT NULL,
    scan_time timestamp with time zone,
    latitude numeric(9,6),
    longitude numeric(9,6),
    notes text,
    employe_id bigint NOT NULL,
    patient_id bigint NOT NULL
);


ALTER TABLE public.api_presence OWNER TO postgres;

--
-- Name: api_presence_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_presence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_presence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_quoteformoption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_quoteformoption (
    id bigint NOT NULL,
    label character varying(200) NOT NULL,
    value character varying(200) NOT NULL,
    price numeric(10,2) NOT NULL,
    "order" integer NOT NULL,
    active boolean NOT NULL,
    allow_custom_text boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    step_id bigint NOT NULL,
    price_enabled boolean NOT NULL,
    parent_id bigint
);


ALTER TABLE public.api_quoteformoption OWNER TO postgres;

--
-- Name: api_quoteformoption_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_quoteformoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_quoteformoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_quoteformstep; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_quoteformstep (
    id bigint NOT NULL,
    step_type character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    description text,
    "order" integer NOT NULL,
    required boolean NOT NULL,
    field_key character varying(100) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.api_quoteformstep OWNER TO postgres;

--
-- Name: api_quoteformstep_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_quoteformstep ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_quoteformstep_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_quoterequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_quoterequest (
    id bigint NOT NULL,
    location character varying(500) NOT NULL,
    location_lat numeric(9,6),
    location_lng numeric(9,6),
    client_name character varying(200) NOT NULL,
    client_email character varying(254) NOT NULL,
    client_phone character varying(20) NOT NULL,
    additional_info jsonb NOT NULL,
    status character varying(20) NOT NULL,
    admin_notes text,
    contacted_at timestamp with time zone,
    quoted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_user_id bigint,
    service_id bigint,
    calculated_price numeric(10,2),
    discount_percentage numeric(5,2)
);


ALTER TABLE public.api_quoterequest OWNER TO postgres;

--
-- Name: api_quoterequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_quoterequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_quoterequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_service (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(200) NOT NULL,
    short_description character varying(500) NOT NULL,
    detailed_description text NOT NULL,
    image character varying(100),
    active boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    duration character varying(100),
    features jsonb NOT NULL,
    guarantees jsonb NOT NULL,
    included_services jsonb NOT NULL,
    price_label character varying(200),
    price_per_hour numeric(10,2),
    process_steps jsonb NOT NULL,
    rating numeric(3,1),
    review_count integer NOT NULL,
    category_id bigint,
    contact_phone character varying(20),
    currency character varying(10) NOT NULL,
    show_faq boolean NOT NULL,
    show_reviews boolean NOT NULL
);


ALTER TABLE public.api_service OWNER TO postgres;

--
-- Name: api_service_agencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_service_agencies (
    id bigint NOT NULL,
    service_id bigint NOT NULL,
    agency_id bigint NOT NULL
);


ALTER TABLE public.api_service_agencies OWNER TO postgres;

--
-- Name: api_service_agencies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_service_agencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_service_agencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_serviceadvantage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_serviceadvantage (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    icon character varying(50) NOT NULL,
    "order" integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.api_serviceadvantage OWNER TO postgres;

--
-- Name: api_serviceadvantage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_serviceadvantage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_serviceadvantage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_servicefaq; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_servicefaq (
    id bigint NOT NULL,
    question character varying(500) NOT NULL,
    answer text NOT NULL,
    "order" integer NOT NULL,
    active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.api_servicefaq OWNER TO postgres;

--
-- Name: api_servicefaq_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_servicefaq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_servicefaq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_servicereview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_servicereview (
    id bigint NOT NULL,
    rating integer NOT NULL,
    comment text NOT NULL,
    client_name character varying(200) NOT NULL,
    client_email character varying(254),
    approved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    service_id bigint NOT NULL,
    user_id bigint,
    display_on_page boolean NOT NULL
);


ALTER TABLE public.api_servicereview OWNER TO postgres;

--
-- Name: api_servicereview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_servicereview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_servicereview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_sitesettings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_sitesettings (
    id bigint NOT NULL,
    primary_color character varying(7) NOT NULL,
    secondary_color character varying(7) NOT NULL,
    tertiary_color character varying(7) NOT NULL,
    logo character varying(100),
    logo_favicon character varying(100),
    site_name character varying(200) NOT NULL,
    site_tagline character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    button_primary_color character varying(7) NOT NULL,
    button_primary_hover_color character varying(7) NOT NULL,
    button_text_color character varying(7) NOT NULL,
    text_link_color character varying(7) NOT NULL,
    text_link_hover_color character varying(7) NOT NULL,
    text_primary_color character varying(7) NOT NULL,
    smtp_host character varying(255),
    smtp_port integer NOT NULL,
    smtp_use_tls boolean NOT NULL,
    smtp_use_ssl boolean NOT NULL,
    smtp_username character varying(255),
    smtp_password character varying(255),
    banner_bg_color character varying(7),
    banner_text_color character varying(7),
    footer_bg_color character varying(7),
    footer_text_color character varying(7),
    footer_link_color character varying(7),
    footer_link_hover_color character varying(7),
    footer_border_color character varying(7),
    button_border_color character varying(7),
    button_border_width integer NOT NULL,
    button_border_radius character varying(20),
    button_outline_border_color character varying(7),
    button_outline_text_color character varying(7),
    button_outline_hover_bg_color character varying(7),
    site_name_part1_color character varying(7),
    site_name_part2_color character varying(7),
    site_tagline_color character varying(7),
    banner_button_color character varying(7),
    banner_button_border_color character varying(7),
    services_bg_color character varying(7),
    services_text_color character varying(7),
    services_button_color character varying(7),
    services_button_border_color character varying(7),
    agencies_bg_color character varying(7),
    agencies_text_color character varying(7),
    agencies_button_color character varying(7),
    agencies_button_border_color character varying(7),
    employe_bg_color character varying(7),
    employe_text_color character varying(7),
    employe_button_color character varying(7),
    employe_button_border_color character varying(7),
    admin_login_bg_color character varying(7),
    admin_login_text_color character varying(7),
    admin_login_button_color character varying(7),
    admin_login_button_border_color character varying(7),
    employe_login_bg_color character varying(7),
    employe_login_text_color character varying(7),
    employe_login_button_color character varying(7),
    employe_login_button_border_color character varying(7),
    logo_area_bg_color character varying(7),
    logo_area_text_color character varying(7),
    devis_pdf_primary_color character varying(7),
    CONSTRAINT api_sitesettings_button_border_width_check CHECK ((button_border_width >= 0))
);


ALTER TABLE public.api_sitesettings OWNER TO postgres;

--
-- Name: api_sitesettings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_sitesettings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_sitesettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: api_agency; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_agency (id, name, slug, address, city, postal_code, phone, email, latitude, longitude, active, details, created_at, updated_at, created_by_id, image, horaires, opening_hours) FROM stdin;
1	Agence Paris	agence-paris	123 Avenue des Champs-Élysées	Paris	75008	+33 1 23 45 67 89	paris@serviceslocaux.ci	48.856600	2.352200	t	Notre siège social à Paris, au cœur de la capitale française.	2026-02-22 18:20:39.504+00	2026-02-24 16:50:24.575493+00	10	agencies/Bouaké_agency_storefront_efadb467.png	\N	\N
2	Agence Abidjan	agence-abidjan	456 Boulevard de la République	Abidjan	01 BP 1234	+225 01 23 45 67 89	abidjan@serviceslocaux.ci	5.360000	-4.008300	t	Notre agence principale en Côte d'Ivoire. , au cœur de la capitale française.	2026-02-22 18:20:39.509+00	2026-02-23 22:42:39.812+00	10	agencies/Gardening_service_photo_0007b568.png		{"jeudi": {"end": "18:00", "open": true, "start": "09:00"}, "lundi": {"end": "18:00", "open": true, "start": "09:00"}, "mardi": {"end": "18:00", "open": true, "start": "09:00"}, "samedi": {"end": "18:00", "open": false, "start": "09:00"}, "dimanche": {"end": "18:00", "open": false, "start": "09:00"}, "mercredi": {"end": "18:00", "open": true, "start": "09:00"}, "vendredi": {"end": "18:00", "open": false, "start": "09:00"}}
3	PROJITASK	projitask	Rue humilité	paris	01 BP 1234	+1 (555) 123-4567	projitask@gmail.com	\N	\N	t	Le slug sera généré	2026-02-23 22:28:58.291+00	2026-02-24 14:16:32.381989+00	9	agencies/Hero_team_photo_c8870b4f.png		{"jeudi": {"end": "18:00", "open": true, "start": "09:00"}, "lundi": {"end": "18:00", "open": false, "start": "09:00"}, "mardi": {"end": "18:00", "open": true, "start": "09:00"}, "samedi": {"end": "18:00", "open": false, "start": "09:00"}, "dimanche": {"end": "18:00", "open": false, "start": "09:00"}, "mercredi": {"end": "18:00", "open": true, "start": "09:00"}, "vendredi": {"end": "18:00", "open": true, "start": "09:00"}}
\.


--
-- Data for Name: api_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_category (id, name, show_in_navbar, "order", created_at, updated_at) FROM stdin;
1	Garde d'enfants	t	1	2026-02-22 18:20:39.362+00	2026-02-22 18:52:14.041+00
2	Ménage et repassage	t	2	2026-02-22 18:20:39.366+00	2026-02-22 18:20:39.366+00
3	Jardinage	t	3	2026-02-22 18:20:39.368+00	2026-02-22 18:20:39.368+00
4	Peinture	t	4	2026-02-22 18:20:39.371+00	2026-02-22 18:52:44.982+00
5	Sécurité	t	5	2026-02-22 18:20:39.374+00	2026-02-22 18:52:46.024+00
6	Déménagement	t	6	2026-02-22 18:20:39.377+00	2026-02-22 18:20:39.377+00
\.


--
-- Data for Name: api_contact; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_contact (id, name, role, phone, email, is_headquarter, address, created_at, updated_at, agency_id, created_by_id) FROM stdin;
1	Contact Siège Paris	Directeur Général	+33 1 23 45 67 89	contact@serviceslocaux.ci	t	123 Avenue des Champs-Élysées, 75008 Paris	2026-02-22 18:20:39.515+00	2026-02-22 18:20:39.515+00	1	10
\.


--
-- Data for Name: api_customuser; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, role, phone, created_at, updated_at, created_by_id, matricule) FROM stdin;
9	pbkdf2_sha256$600000$0Mh2QpElX0azFZg5R7wmdT$BnrHYiA8jJ8WjQ1HgguQ8gHbooVLEZ/K6GfqGawGX9M=	\N	t	superadmin			super@local.test	t	t	2026-02-22 18:20:39.083+00	SUPERADMIN	\N	2026-02-22 18:20:39.194+00	2026-02-22 18:20:39.194+00	\N	\N
10	pbkdf2_sha256$600000$7BT2ss3ejoK9R9pZ2ldtVF$FdwYlMwAIgybibOJE1lpneUKRrjsaq3OvjBkCYiZnSc=	\N	f	admin			admin@local.test	t	t	2026-02-22 18:20:39.202+00	ADMIN	\N	2026-02-22 18:20:39.31+00	2026-02-22 18:20:39.31+00	\N	\N
11	pbkdf2_sha256$600000$9JjjhgYMxlv2emZjfbbKjy$C0gEWcEx5rl/b75mPSmCpw1zxylMv6idxDf6LcM5kw4=	\N	f	client			client@local.test	f	t	2026-02-22 18:20:39.379+00	CLIENT	\N	2026-02-22 18:20:39.487+00	2026-02-22 18:20:39.487+00	\N	\N
12	pbkdf2_sha256$600000$PFuM5zT9Gr0nQyBe4yWEc3$1HbvhTpw+PN+j3Hly2tskWgewA0eHLxIuKfKB5qUcc4=	\N	f	salami	abiola	salami	issouf.fof0@gmail.com	f	t	2026-02-23 22:04:54.685+00	EMPLOYE	\N	2026-02-23 22:04:54.803+00	2026-02-25 07:17:35.586682+00	9	0101
\.


--
-- Data for Name: api_customuser_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: api_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
57	10	9
58	10	10
59	10	11
60	10	12
61	10	21
62	10	22
63	10	23
64	10	24
65	10	25
66	10	26
67	10	27
68	10	28
69	10	29
70	10	30
71	10	31
72	10	32
73	10	33
74	10	34
75	10	35
76	10	36
77	10	37
78	10	38
79	10	39
80	10	40
81	10	41
82	10	42
83	10	43
84	10	44
\.


--
-- Data for Name: api_employeeprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_employeeprofile (id, sexe, date_naissance, nationalite, photo_profil, signature, email_professionnel, email_personnel, telephone_principal, telephone_secondaire, adresse_numero_rue, adresse_ville, adresse_code_postal, adresse_pays, statut_compte, derniere_connexion, tentatives_connexion_echouees, appareil_utilise, ip_derniere_connexion, poste_fonction, service_departement, type_contrat, date_debut_contrat, date_fin_contrat, temps_travail, taux_horaire, salaire, mode_paiement, numero_securite_sociale, numero_employe_interne, contrat_signe, avenants, clause_non_concurrence, note_information, piece_identite, diplomes_certifications, documents_administratifs, date_signature_electronique, statut_documents, created_at, updated_at, user_id) FROM stdin;
1	M	2026-02-23	fr			issouf.fof0@gmail.com	issouf.fof0@gmail.com	01010101	01010101	010	ab	01	ci	ACTIF	\N	0	\N	\N	admin sys	informatique	CDI	2026-02-03	\N	PLEIN	20.00	25000.00	VIREMENT	121	212								\N	EN_ATTENTE	2026-02-23 22:04:54.818+00	2026-02-25 07:17:09.749611+00	12
\.


--
-- Data for Name: api_invoice; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_invoice (id, invoice_number, subtotal, tax_rate, tax_amount, total, currency, invoice_date, due_date, notes, payment_terms, created_at, updated_at, created_by_id, quote_request_id) FROM stdin;
\.


--
-- Data for Name: api_pagecontent; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_pagecontent (id, key, title, body, is_active, "order", created_at, updated_at, created_by_id, button_link_type, button_text, button_url) FROM stdin;
1	home_banner	Bande annonce	Réduisez votre facture de moitié avec l'avance immédiate de crédit d'impôt*	t	1	2026-02-22 18:20:39.521+00	2026-02-22 22:33:28.45+00	10	devis	J'en profite !	\N
4	cc	c	Réduisez votre facture de moitié avec l'avance immédiate de crédit d'impôt*	f	0	2026-02-22 22:33:50.789+00	2026-02-22 22:34:04.679+00	9	devis	J'en profite !	\N
\.


--
-- Data for Name: api_patient; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_patient (id, first_name, last_name, phone, address, qr_code, qr_code_image, is_active, created_at, updated_at, client_id, created_by_id) FROM stdin;
1	ISSOUF	FOFANA	0759177681	\N	3247053F14F44797530004CC328B6741		t	2026-02-23 22:07:14.695+00	2026-02-23 22:07:14.695+00	9	9
\.


--
-- Data for Name: api_patient_assigned_employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_patient_assigned_employees (id, patient_id, customuser_id) FROM stdin;
1	1	12
\.


--
-- Data for Name: api_presence; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_presence (id, status, scan_time, latitude, longitude, notes, employe_id, patient_id) FROM stdin;
1	ARRIVEE	2026-02-23 22:10:19.681+00	5.420948	-4.024773		12	1
2	DEPART	2026-02-23 22:10:56.501+00	5.420949	-4.024768		12	1
\.


--
-- Data for Name: api_quoteformoption; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_quoteformoption (id, label, value, price, "order", active, allow_custom_text, created_at, updated_at, step_id, price_enabled, parent_id) FROM stdin;
2	cuisine	menage	120.00	0	t	f	2026-02-22 19:07:17.286+00	2026-02-22 19:07:17.286+00	1	t	\N
\.


--
-- Data for Name: api_quoteformstep; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_quoteformstep (id, step_type, title, description, "order", required, field_key, active, created_at, updated_at, service_id) FROM stdin;
1	SINGLE_CHOICE	Nettoyage maison	Nettoyage maison, Nettoyage maison	0	f	maison	t	2026-02-22 18:58:50.37+00	2026-02-22 19:09:14.036+00	1
\.


--
-- Data for Name: api_quoterequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_quoterequest (id, location, location_lat, location_lng, client_name, client_email, client_phone, additional_info, status, admin_notes, contacted_at, quoted_at, created_at, updated_at, created_by_user_id, service_id, calculated_price, discount_percentage) FROM stdin;
2	cocody 2	\N	\N	youssef fofana	youssef.anonymous0@gmail.com	+2250759177681	{"maison": "menage", "message": "Un devis est un document écrit détaillant les prestations ou produits proposés par un professionnel, transmit au client pour information ou accord; il devient contractuel une fois signé"}	QUOTED	\N	\N	2026-02-23 22:16:22.993+00	2026-02-23 22:15:08.974+00	2026-02-23 22:16:22.993+00	\N	1	145.00	10.00
1	abidjan	\N	\N	ISSOUF FOFANA	issouf.fof0@gmail.com	6666666665	{"maison": "menage", "message": "issouf.fof0@gmail.comissouf.fof0@gmail.comissouf.fof0@gmail.comissouf.fof0@gmail.com"}	QUOTED	\N	\N	2026-02-23 21:11:13.03+00	2026-02-22 19:15:44.599+00	2026-02-24 16:57:41.39822+00	\N	1	145.00	5.00
\.


--
-- Data for Name: api_service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_service (id, name, slug, short_description, detailed_description, image, active, "order", created_at, updated_at, created_by_id, duration, features, guarantees, included_services, price_label, price_per_hour, process_steps, rating, review_count, category_id, contact_phone, currency, show_faq, show_reviews) FROM stdin;
2	Garde d'enfants à domicile	garde-enfants-domicile	Des nounous qualifiées et bienveillantes pour prendre soin de vos petits trésors.	Service premium de garde d'enfants à domicile, flexible et sécurisé. Nos nounous sont formées et certifiées.	services/Bouaké_agency_storefront_efadb467.png	t	2	2026-02-22 18:20:39.499+00	2026-02-22 18:46:02.167+00	10	\N	[]	[]	[]	\N	\N	[{"step": 1, "title": "Nous aimons vous rendre la vie plus facile", "description": "Nous aimons vous rendre la vie plus facile Nous aimons vous rendre la vie plus facile"}]	5.0	1	1	\N	EUR	t	t
1	Nettoyage résidentiel	nettoyage-residentiel	Un service complet pour que votre maison brille du sol au plafond.	Nos professionnels utilisent des produits écologiques et des techniques éprouvées pour un résultat impeccable. Chaque intervention est personnalisée selon vos besoins spécifiques.	services/Gardening_service_photo_0007b568_V5WDzj5.png	t	1	2026-02-22 18:20:39.493+00	2026-02-24 08:26:15.155937+00	10	2 - 4heures	[]	[]	[]	A partir de 20 £	25.00	[]	\N	0	2	+225 07 59 17 76 81	EUR	t	t
\.


--
-- Data for Name: api_service_agencies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_service_agencies (id, service_id, agency_id) FROM stdin;
9	1	1
10	1	2
11	2	2
12	2	3
\.


--
-- Data for Name: api_serviceadvantage; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_serviceadvantage (id, title, description, icon, "order", active, created_at, updated_at) FROM stdin;
1	Professionnels certifiés	Tous nos intervenants sont sélectionnés, formés et régulièrement évalués	FaShieldAlt	0	t	2026-02-22 19:16:44.087+00	2026-02-22 19:16:44.087+00
2	Professionnels certifiés	Tous nos intervenants sont sélectionnés, formés et régulièrement évalués	FaUsers	1	t	2026-02-22 19:17:02.045+00	2026-02-22 19:17:02.045+00
3	Professionnels certifiés	Tous nos intervenants sont sélectionnés, formés et régulièrement évalués	FaEnvelope	3	t	2026-02-22 19:17:24.922+00	2026-02-22 19:17:24.922+00
4	Professionnels certifiés	Tous nos intervenants sont sélectionnés, formés et régulièrement évalués	FaAward	4	t	2026-02-22 19:17:45.638+00	2026-02-22 19:17:45.638+00
\.


--
-- Data for Name: api_servicefaq; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_servicefaq (id, question, answer, "order", active, created_at, updated_at, service_id) FROM stdin;
\.


--
-- Data for Name: api_servicereview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_servicereview (id, rating, comment, client_name, client_email, approved, created_at, updated_at, service_id, user_id, display_on_page) FROM stdin;
1	5	très bon service	alien	alien@gmail.com	t	2026-02-23 22:18:32.262+00	2026-02-23 22:26:00.036+00	2	\N	t
\.


--
-- Data for Name: api_sitesettings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_sitesettings (id, primary_color, secondary_color, tertiary_color, logo, logo_favicon, site_name, site_tagline, created_at, updated_at, button_primary_color, button_primary_hover_color, button_text_color, text_link_color, text_link_hover_color, text_primary_color, smtp_host, smtp_port, smtp_use_tls, smtp_use_ssl, smtp_username, smtp_password, banner_bg_color, banner_text_color, footer_bg_color, footer_text_color, footer_link_color, footer_link_hover_color, footer_border_color, button_border_color, button_border_width, button_border_radius, button_outline_border_color, button_outline_text_color, button_outline_hover_bg_color, site_name_part1_color, site_name_part2_color, site_tagline_color, banner_button_color, banner_button_border_color, services_bg_color, services_text_color, services_button_color, services_button_border_color, agencies_bg_color, agencies_text_color, agencies_button_color, agencies_button_border_color, employe_bg_color, employe_text_color, employe_button_color, employe_button_border_color, admin_login_bg_color, admin_login_text_color, admin_login_button_color, admin_login_button_border_color, employe_login_bg_color, employe_login_text_color, employe_login_button_color, employe_login_button_border_color, logo_area_bg_color, logo_area_text_color, devis_pdf_primary_color) FROM stdin;
1	#087A00	#066300	#044000	site/LOGO.png	site/LOGO_xXAdw8r.png	EASE - DOM	Votre partenaire de confiance	2026-02-22 18:16:42.987+00	2026-02-25 06:55:35.706245+00	#087A00	#066300	#FFFFFF	#087A00	#066300	#087A00	smtp.gmail.com	465	f	t	issouf.fofana.pro@gmail.com	gxvwifedvgemdrge	#087A00	#FFFFFF	#F0FDF4	#374151	#087A00	#066300	#BBF7D0		0	0.375rem	#087A00	#087A00	#087A00	#111827	#087A00	#6B7280	#087A00		#087A00	#FFFFFF	#087A00		#087A00	#FFFFFF	#087A00		#087A00	#FFFFFF	#087A00		#087A00	#FFFFFF	#087A00		#087A00	#FFFFFF	#087A00				#087A00
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Utilisateur	6	add_customuser
22	Can change Utilisateur	6	change_customuser
23	Can delete Utilisateur	6	delete_customuser
24	Can view Utilisateur	6	view_customuser
25	Can add Agence	7	add_agency
26	Can change Agence	7	change_agency
27	Can delete Agence	7	delete_agency
28	Can view Agence	7	view_agency
29	Can add Service	8	add_service
30	Can change Service	8	change_service
31	Can delete Service	8	delete_service
32	Can view Service	8	view_service
33	Can add Contenu de page	9	add_pagecontent
34	Can change Contenu de page	9	change_pagecontent
35	Can delete Contenu de page	9	delete_pagecontent
36	Can view Contenu de page	9	view_pagecontent
37	Can add Contact	10	add_contact
38	Can change Contact	10	change_contact
39	Can delete Contact	10	delete_contact
40	Can view Contact	10	view_contact
41	Can add Catégorie	11	add_category
42	Can change Catégorie	11	change_category
43	Can delete Catégorie	11	delete_category
44	Can view Catégorie	11	view_category
45	Can add Avis client	12	add_servicereview
46	Can change Avis client	12	change_servicereview
47	Can delete Avis client	12	delete_servicereview
48	Can view Avis client	12	view_servicereview
49	Can add Question fréquente	13	add_servicefaq
50	Can change Question fréquente	13	change_servicefaq
51	Can delete Question fréquente	13	delete_servicefaq
52	Can view Question fréquente	13	view_servicefaq
53	Can add Demande de devis	14	add_quoterequest
54	Can change Demande de devis	14	change_quoterequest
55	Can delete Demande de devis	14	delete_quoterequest
56	Can view Demande de devis	14	view_quoterequest
57	Can add Avantage service	15	add_serviceadvantage
58	Can change Avantage service	15	change_serviceadvantage
59	Can delete Avantage service	15	delete_serviceadvantage
60	Can view Avantage service	15	view_serviceadvantage
61	Can add Paramètres du site	16	add_sitesettings
62	Can change Paramètres du site	16	change_sitesettings
63	Can delete Paramètres du site	16	delete_sitesettings
64	Can view Paramètres du site	16	view_sitesettings
65	Can add Facture	17	add_invoice
66	Can change Facture	17	change_invoice
67	Can delete Facture	17	delete_invoice
68	Can view Facture	17	view_invoice
69	Can add Étape du formulaire de devis	18	add_quoteformstep
70	Can change Étape du formulaire de devis	18	change_quoteformstep
71	Can delete Étape du formulaire de devis	18	delete_quoteformstep
72	Can view Étape du formulaire de devis	18	view_quoteformstep
73	Can add Option du formulaire	19	add_quoteformoption
74	Can change Option du formulaire	19	change_quoteformoption
75	Can delete Option du formulaire	19	delete_quoteformoption
76	Can view Option du formulaire	19	view_quoteformoption
77	Can add Patient	20	add_patient
78	Can change Patient	20	change_patient
79	Can delete Patient	20	delete_patient
80	Can view Patient	20	view_patient
81	Can add Présence	21	add_presence
82	Can change Présence	21	change_presence
83	Can delete Présence	21	delete_presence
84	Can view Présence	21	view_presence
85	Can add Profil employé	22	add_employeeprofile
86	Can change Profil employé	22	change_employeeprofile
87	Can delete Profil employé	22	delete_employeeprofile
88	Can view Profil employé	22	view_employeeprofile
89	Can add Bloc de contenu	23	add_contentblock
90	Can change Bloc de contenu	23	change_contentblock
91	Can delete Bloc de contenu	23	delete_contentblock
92	Can view Bloc de contenu	23	view_contentblock
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	api	customuser
7	api	agency
8	api	service
9	api	pagecontent
10	api	contact
11	api	category
12	api	servicereview
13	api	servicefaq
14	api	quoterequest
15	api	serviceadvantage
16	api	sitesettings
17	api	invoice
18	api	quoteformstep
19	api	quoteformoption
20	api	patient
21	api	presence
22	api	employeeprofile
23	content	contentblock
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-24 00:10:03.767812+00
2	contenttypes	0002_remove_content_type_name	2026-02-24 00:10:03.786143+00
3	auth	0001_initial	2026-02-24 00:10:03.967754+00
4	auth	0002_alter_permission_name_max_length	2026-02-24 00:10:03.976528+00
5	auth	0003_alter_user_email_max_length	2026-02-24 00:10:03.983831+00
6	auth	0004_alter_user_username_opts	2026-02-24 00:10:03.992903+00
7	auth	0005_alter_user_last_login_null	2026-02-24 00:10:04.005765+00
8	auth	0006_require_contenttypes_0002	2026-02-24 00:10:04.011089+00
9	auth	0007_alter_validators_add_error_messages	2026-02-24 00:10:04.019881+00
10	auth	0008_alter_user_username_max_length	2026-02-24 00:10:04.028114+00
11	auth	0009_alter_user_last_name_max_length	2026-02-24 00:10:04.036695+00
12	auth	0010_alter_group_name_max_length	2026-02-24 00:10:04.055323+00
13	auth	0011_update_proxy_permissions	2026-02-24 00:10:04.0781+00
14	auth	0012_alter_user_first_name_max_length	2026-02-24 00:10:04.088487+00
15	api	0001_initial	2026-02-24 00:10:04.4703+00
16	admin	0001_initial	2026-02-24 00:10:04.523296+00
17	admin	0002_logentry_remove_auto_add	2026-02-24 00:10:04.534494+00
18	admin	0003_logentry_add_action_flag_choices	2026-02-24 00:10:04.547072+00
19	api	0002_service_duration_service_features_service_guarantees_and_more	2026-02-24 00:10:04.665303+00
20	api	0003_service_category	2026-02-24 00:10:04.696894+00
21	api	0004_category_alter_service_category	2026-02-24 00:10:04.784545+00
22	api	0005_servicereview_servicefaq	2026-02-24 00:10:04.8613+00
23	api	0006_service_contact_phone_service_currency	2026-02-24 00:10:04.937004+00
24	api	0007_service_show_faq_service_show_reviews	2026-02-24 00:10:04.96821+00
25	api	0008_servicereview_display_on_page	2026-02-24 00:10:04.986322+00
26	api	0009_quoterequest	2026-02-24 00:10:05.047226+00
27	api	0010_serviceadvantage	2026-02-24 00:10:05.070381+00
28	api	0011_agency_image	2026-02-24 00:10:05.085357+00
29	api	0012_service_agencies	2026-02-24 00:10:05.12319+00
30	api	0013_sitesettings	2026-02-24 00:10:05.135312+00
31	api	0014_sitesettings_button_primary_color_and_more	2026-02-24 00:10:05.163329+00
32	api	0015_invoice	2026-02-24 00:10:05.221381+00
33	api	0016_alter_invoice_invoice_number	2026-02-24 00:10:05.236994+00
34	api	0017_quoterequest_calculated_price_quoteformstep_and_more	2026-02-24 00:10:05.314442+00
35	api	0018_quoteformoption_price_enabled_and_more	2026-02-24 00:10:05.342229+00
36	api	0019_alter_quoteformoption_options_quoteformoption_parent	2026-02-24 00:10:05.372434+00
37	api	0020_sitesettings_smtp_config	2026-02-24 00:10:05.389698+00
38	api	0021_quoterequest_service_optional	2026-02-24 00:10:05.429387+00
39	api	0022_patient_presence_alter_quoteformoption_options_and_more	2026-02-24 00:10:05.818683+00
40	api	0023_employeeprofile	2026-02-24 00:10:05.919368+00
41	api	0024_alter_presence_scan_time	2026-02-24 00:10:05.956263+00
42	api	0025_patient_assigned_employees	2026-02-24 00:10:06.046155+00
43	api	0026_sitesettings_banner_footer_button_border	2026-02-24 00:10:06.191585+00
44	api	0027_sitesettings_slogan_outline_buttons	2026-02-24 00:10:06.222984+00
45	api	0028_sitesettings_section_colors	2026-02-24 00:10:06.342656+00
46	api	0029_sitesettings_logo_devis_pdf_colors	2026-02-24 00:10:06.364258+00
47	api	0030_sitesettings_default_green	2026-02-24 00:10:06.395163+00
48	api	0030_alter_sitesettings_button_border_color	2026-02-24 00:10:06.400393+00
49	api	0035_merge_0030_migrations	2026-02-24 00:10:06.405448+00
50	sessions	0001_initial	2026-02-24 00:10:06.428821+00
51	api	0036_agency_horaires_opening_hours	2026-02-24 00:11:38.609744+00
52	api	0037_pagecontent_button_fields	2026-02-24 00:13:03.845971+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: api_agency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_agency_id_seq', 4, true);


--
-- Name: api_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_category_id_seq', 6, true);


--
-- Name: api_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_contact_id_seq', 1, true);


--
-- Name: api_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_customuser_groups_id_seq', 1, false);


--
-- Name: api_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_customuser_id_seq', 12, true);


--
-- Name: api_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_customuser_user_permissions_id_seq', 84, true);


--
-- Name: api_employeeprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_employeeprofile_id_seq', 1, true);


--
-- Name: api_invoice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_invoice_id_seq', 1, false);


--
-- Name: api_pagecontent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_pagecontent_id_seq', 4, true);


--
-- Name: api_patient_assigned_employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_patient_assigned_employees_id_seq', 1, true);


--
-- Name: api_patient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_patient_id_seq', 1, true);


--
-- Name: api_presence_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_presence_id_seq', 2, true);


--
-- Name: api_quoteformoption_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_quoteformoption_id_seq', 2, true);


--
-- Name: api_quoteformstep_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_quoteformstep_id_seq', 1, true);


--
-- Name: api_quoterequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_quoterequest_id_seq', 2, true);


--
-- Name: api_service_agencies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_service_agencies_id_seq', 13, true);


--
-- Name: api_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_service_id_seq', 3, true);


--
-- Name: api_serviceadvantage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_serviceadvantage_id_seq', 4, true);


--
-- Name: api_servicefaq_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_servicefaq_id_seq', 1, false);


--
-- Name: api_servicereview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_servicereview_id_seq', 1, true);


--
-- Name: api_sitesettings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_sitesettings_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 92, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 23, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 52, true);


--
-- Name: api_agency api_agency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_agency
    ADD CONSTRAINT api_agency_pkey PRIMARY KEY (id);


--
-- Name: api_agency api_agency_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_agency
    ADD CONSTRAINT api_agency_slug_key UNIQUE (slug);


--
-- Name: api_category api_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_category
    ADD CONSTRAINT api_category_name_key UNIQUE (name);


--
-- Name: api_category api_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_category
    ADD CONSTRAINT api_category_pkey PRIMARY KEY (id);


--
-- Name: api_contact api_contact_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_contact
    ADD CONSTRAINT api_contact_pkey PRIMARY KEY (id);


--
-- Name: api_customuser_groups api_customuser_groups_customuser_id_group_id_d5b0c2ab_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_groups
    ADD CONSTRAINT api_customuser_groups_customuser_id_group_id_d5b0c2ab_uniq UNIQUE (customuser_id, group_id);


--
-- Name: api_customuser_groups api_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_groups
    ADD CONSTRAINT api_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: api_customuser api_customuser_matricule_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser
    ADD CONSTRAINT api_customuser_matricule_key UNIQUE (matricule);


--
-- Name: api_customuser api_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser
    ADD CONSTRAINT api_customuser_pkey PRIMARY KEY (id);


--
-- Name: api_customuser_user_permissions api_customuser_user_perm_customuser_id_permission_9deacd8d_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_user_permissions
    ADD CONSTRAINT api_customuser_user_perm_customuser_id_permission_9deacd8d_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: api_customuser_user_permissions api_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_user_permissions
    ADD CONSTRAINT api_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: api_customuser api_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser
    ADD CONSTRAINT api_customuser_username_key UNIQUE (username);


--
-- Name: api_employeeprofile api_employeeprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_employeeprofile
    ADD CONSTRAINT api_employeeprofile_pkey PRIMARY KEY (id);


--
-- Name: api_employeeprofile api_employeeprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_employeeprofile
    ADD CONSTRAINT api_employeeprofile_user_id_key UNIQUE (user_id);


--
-- Name: api_invoice api_invoice_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_invoice
    ADD CONSTRAINT api_invoice_invoice_number_key UNIQUE (invoice_number);


--
-- Name: api_invoice api_invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_invoice
    ADD CONSTRAINT api_invoice_pkey PRIMARY KEY (id);


--
-- Name: api_invoice api_invoice_quote_request_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_invoice
    ADD CONSTRAINT api_invoice_quote_request_id_key UNIQUE (quote_request_id);


--
-- Name: api_pagecontent api_pagecontent_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_pagecontent
    ADD CONSTRAINT api_pagecontent_key_key UNIQUE (key);


--
-- Name: api_pagecontent api_pagecontent_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_pagecontent
    ADD CONSTRAINT api_pagecontent_pkey PRIMARY KEY (id);


--
-- Name: api_patient_assigned_employees api_patient_assigned_emp_patient_id_customuser_id_2ae4132e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient_assigned_employees
    ADD CONSTRAINT api_patient_assigned_emp_patient_id_customuser_id_2ae4132e_uniq UNIQUE (patient_id, customuser_id);


--
-- Name: api_patient_assigned_employees api_patient_assigned_employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient_assigned_employees
    ADD CONSTRAINT api_patient_assigned_employees_pkey PRIMARY KEY (id);


--
-- Name: api_patient api_patient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient
    ADD CONSTRAINT api_patient_pkey PRIMARY KEY (id);


--
-- Name: api_patient api_patient_qr_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient
    ADD CONSTRAINT api_patient_qr_code_key UNIQUE (qr_code);


--
-- Name: api_presence api_presence_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_presence
    ADD CONSTRAINT api_presence_pkey PRIMARY KEY (id);


--
-- Name: api_quoteformoption api_quoteformoption_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoteformoption
    ADD CONSTRAINT api_quoteformoption_pkey PRIMARY KEY (id);


--
-- Name: api_quoteformstep api_quoteformstep_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoteformstep
    ADD CONSTRAINT api_quoteformstep_pkey PRIMARY KEY (id);


--
-- Name: api_quoteformstep api_quoteformstep_service_id_field_key_c9b897ac_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoteformstep
    ADD CONSTRAINT api_quoteformstep_service_id_field_key_c9b897ac_uniq UNIQUE (service_id, field_key);


--
-- Name: api_quoterequest api_quoterequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoterequest
    ADD CONSTRAINT api_quoterequest_pkey PRIMARY KEY (id);


--
-- Name: api_service_agencies api_service_agencies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service_agencies
    ADD CONSTRAINT api_service_agencies_pkey PRIMARY KEY (id);


--
-- Name: api_service_agencies api_service_agencies_service_id_agency_id_20dcd262_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service_agencies
    ADD CONSTRAINT api_service_agencies_service_id_agency_id_20dcd262_uniq UNIQUE (service_id, agency_id);


--
-- Name: api_service api_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service
    ADD CONSTRAINT api_service_pkey PRIMARY KEY (id);


--
-- Name: api_service api_service_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service
    ADD CONSTRAINT api_service_slug_key UNIQUE (slug);


--
-- Name: api_serviceadvantage api_serviceadvantage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_serviceadvantage
    ADD CONSTRAINT api_serviceadvantage_pkey PRIMARY KEY (id);


--
-- Name: api_servicefaq api_servicefaq_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_servicefaq
    ADD CONSTRAINT api_servicefaq_pkey PRIMARY KEY (id);


--
-- Name: api_servicereview api_servicereview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_servicereview
    ADD CONSTRAINT api_servicereview_pkey PRIMARY KEY (id);


--
-- Name: api_sitesettings api_sitesettings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_sitesettings
    ADD CONSTRAINT api_sitesettings_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_agency_active_31191260; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_agency_active_31191260 ON public.api_agency USING btree (active);


--
-- Name: api_agency_active_74d292_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_agency_active_74d292_idx ON public.api_agency USING btree (active);


--
-- Name: api_agency_created_by_id_002c2d46; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_agency_created_by_id_002c2d46 ON public.api_agency USING btree (created_by_id);


--
-- Name: api_agency_latitud_b66b29_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_agency_latitud_b66b29_idx ON public.api_agency USING btree (latitude, longitude);


--
-- Name: api_agency_slug_073045_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_agency_slug_073045_idx ON public.api_agency USING btree (slug);


--
-- Name: api_agency_slug_e80f44ca_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_agency_slug_e80f44ca_like ON public.api_agency USING btree (slug varchar_pattern_ops);


--
-- Name: api_category_name_4aabb41f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_category_name_4aabb41f_like ON public.api_category USING btree (name varchar_pattern_ops);


--
-- Name: api_category_order_9cf4068e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_category_order_9cf4068e ON public.api_category USING btree ("order");


--
-- Name: api_contact_agency__15b3df_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_contact_agency__15b3df_idx ON public.api_contact USING btree (agency_id);


--
-- Name: api_contact_agency_id_d7d4ae04; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_contact_agency_id_d7d4ae04 ON public.api_contact USING btree (agency_id);


--
-- Name: api_contact_created_by_id_550e483b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_contact_created_by_id_550e483b ON public.api_contact USING btree (created_by_id);


--
-- Name: api_contact_is_head_6e6473_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_contact_is_head_6e6473_idx ON public.api_contact USING btree (is_headquarter);


--
-- Name: api_contact_is_headquarter_2d69a763; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_contact_is_headquarter_2d69a763 ON public.api_contact USING btree (is_headquarter);


--
-- Name: api_customu_matricu_eed217_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customu_matricu_eed217_idx ON public.api_customuser USING btree (matricule);


--
-- Name: api_customu_role_3dda3d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customu_role_3dda3d_idx ON public.api_customuser USING btree (role);


--
-- Name: api_customuser_created_by_id_fbaeaeef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_created_by_id_fbaeaeef ON public.api_customuser USING btree (created_by_id);


--
-- Name: api_customuser_groups_customuser_id_9eb4b783; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_groups_customuser_id_9eb4b783 ON public.api_customuser_groups USING btree (customuser_id);


--
-- Name: api_customuser_groups_group_id_f049027c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_groups_group_id_f049027c ON public.api_customuser_groups USING btree (group_id);


--
-- Name: api_customuser_matricule_a969920f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_matricule_a969920f_like ON public.api_customuser USING btree (matricule varchar_pattern_ops);


--
-- Name: api_customuser_user_permissions_customuser_id_5365c9ba; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_user_permissions_customuser_id_5365c9ba ON public.api_customuser_user_permissions USING btree (customuser_id);


--
-- Name: api_customuser_user_permissions_permission_id_8735d73e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_user_permissions_permission_id_8735d73e ON public.api_customuser_user_permissions USING btree (permission_id);


--
-- Name: api_customuser_username_f5ae5d7f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_customuser_username_f5ae5d7f_like ON public.api_customuser USING btree (username varchar_pattern_ops);


--
-- Name: api_invoice_created_by_id_2da52342; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_invoice_created_by_id_2da52342 ON public.api_invoice USING btree (created_by_id);


--
-- Name: api_invoice_invoice_59a3b3_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_invoice_invoice_59a3b3_idx ON public.api_invoice USING btree (invoice_number);


--
-- Name: api_invoice_invoice_f212df_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_invoice_invoice_f212df_idx ON public.api_invoice USING btree (invoice_date DESC);


--
-- Name: api_invoice_invoice_number_431ad2aa_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_invoice_invoice_number_431ad2aa_like ON public.api_invoice USING btree (invoice_number varchar_pattern_ops);


--
-- Name: api_invoice_quote_r_5a66fe_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_invoice_quote_r_5a66fe_idx ON public.api_invoice USING btree (quote_request_id);


--
-- Name: api_pagecon_is_acti_a51e7a_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_pagecon_is_acti_a51e7a_idx ON public.api_pagecontent USING btree (is_active, "order");


--
-- Name: api_pagecon_key_8c4cd9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_pagecon_key_8c4cd9_idx ON public.api_pagecontent USING btree (key);


--
-- Name: api_pagecontent_created_by_id_5091b166; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_pagecontent_created_by_id_5091b166 ON public.api_pagecontent USING btree (created_by_id);


--
-- Name: api_pagecontent_is_active_223fbec5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_pagecontent_is_active_223fbec5 ON public.api_pagecontent USING btree (is_active);


--
-- Name: api_pagecontent_key_585eb4c3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_pagecontent_key_585eb4c3_like ON public.api_pagecontent USING btree (key varchar_pattern_ops);


--
-- Name: api_pagecontent_order_aaba0cd6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_pagecontent_order_aaba0cd6 ON public.api_pagecontent USING btree ("order");


--
-- Name: api_patient_assigned_employees_customuser_id_c3ba6567; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_assigned_employees_customuser_id_c3ba6567 ON public.api_patient_assigned_employees USING btree (customuser_id);


--
-- Name: api_patient_assigned_employees_patient_id_d2b97ec2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_assigned_employees_patient_id_d2b97ec2 ON public.api_patient_assigned_employees USING btree (patient_id);


--
-- Name: api_patient_client__8752a7_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_client__8752a7_idx ON public.api_patient USING btree (client_id, is_active);


--
-- Name: api_patient_client_id_4b1d6178; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_client_id_4b1d6178 ON public.api_patient USING btree (client_id);


--
-- Name: api_patient_created_by_id_57cbf8d3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_created_by_id_57cbf8d3 ON public.api_patient USING btree (created_by_id);


--
-- Name: api_patient_qr_code_69390679_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_qr_code_69390679_like ON public.api_patient USING btree (qr_code varchar_pattern_ops);


--
-- Name: api_patient_qr_code_fb2df5_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_patient_qr_code_fb2df5_idx ON public.api_patient USING btree (qr_code);


--
-- Name: api_presenc_employe_7d9635_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_presenc_employe_7d9635_idx ON public.api_presence USING btree (employe_id, scan_time);


--
-- Name: api_presenc_patient_b3d5f4_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_presenc_patient_b3d5f4_idx ON public.api_presence USING btree (patient_id, scan_time);


--
-- Name: api_presenc_status_110670_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_presenc_status_110670_idx ON public.api_presence USING btree (status, scan_time);


--
-- Name: api_presence_employe_id_1f76278e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_presence_employe_id_1f76278e ON public.api_presence USING btree (employe_id);


--
-- Name: api_presence_patient_id_fe27ba5c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_presence_patient_id_fe27ba5c ON public.api_presence USING btree (patient_id);


--
-- Name: api_quoteformoption_order_47f9b11f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoteformoption_order_47f9b11f ON public.api_quoteformoption USING btree ("order");


--
-- Name: api_quoteformoption_parent_id_2edec2f9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoteformoption_parent_id_2edec2f9 ON public.api_quoteformoption USING btree (parent_id);


--
-- Name: api_quoteformoption_step_id_e088f7df; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoteformoption_step_id_e088f7df ON public.api_quoteformoption USING btree (step_id);


--
-- Name: api_quoteformstep_order_279deb4c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoteformstep_order_279deb4c ON public.api_quoteformstep USING btree ("order");


--
-- Name: api_quoteformstep_service_id_9b80a884; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoteformstep_service_id_9b80a884 ON public.api_quoteformstep USING btree (service_id);


--
-- Name: api_quotere_service_4dad92_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quotere_service_4dad92_idx ON public.api_quoterequest USING btree (service_id, status);


--
-- Name: api_quotere_status_6fe288_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quotere_status_6fe288_idx ON public.api_quoterequest USING btree (status, created_at DESC);


--
-- Name: api_quoterequest_created_by_user_id_d39b68c5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoterequest_created_by_user_id_d39b68c5 ON public.api_quoterequest USING btree (created_by_user_id);


--
-- Name: api_quoterequest_service_id_98f70f85; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoterequest_service_id_98f70f85 ON public.api_quoterequest USING btree (service_id);


--
-- Name: api_quoterequest_status_08ebf931; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoterequest_status_08ebf931 ON public.api_quoterequest USING btree (status);


--
-- Name: api_quoterequest_status_08ebf931_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_quoterequest_status_08ebf931_like ON public.api_quoterequest USING btree (status varchar_pattern_ops);


--
-- Name: api_service_active_4dafd2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_active_4dafd2_idx ON public.api_service USING btree (active, "order");


--
-- Name: api_service_active_559687_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_active_559687_idx ON public.api_serviceadvantage USING btree (active, "order");


--
-- Name: api_service_active_c88848c8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_active_c88848c8 ON public.api_service USING btree (active);


--
-- Name: api_service_agencies_agency_id_893f471b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_agencies_agency_id_893f471b ON public.api_service_agencies USING btree (agency_id);


--
-- Name: api_service_agencies_service_id_2fc1f491; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_agencies_service_id_2fc1f491 ON public.api_service_agencies USING btree (service_id);


--
-- Name: api_service_approve_f375b0_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_approve_f375b0_idx ON public.api_servicereview USING btree (approved, created_at DESC);


--
-- Name: api_service_category_c05e4975; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_category_c05e4975 ON public.api_service USING btree (category_id);


--
-- Name: api_service_created_by_id_0510348a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_created_by_id_0510348a ON public.api_service USING btree (created_by_id);


--
-- Name: api_service_order_5999cfa3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_order_5999cfa3 ON public.api_service USING btree ("order");


--
-- Name: api_service_service_7f0957_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_service_7f0957_idx ON public.api_servicefaq USING btree (service_id, active, "order");


--
-- Name: api_service_service_f21329_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_service_f21329_idx ON public.api_servicereview USING btree (service_id, approved);


--
-- Name: api_service_slug_142ea7_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_slug_142ea7_idx ON public.api_service USING btree (slug);


--
-- Name: api_service_slug_dacaebc3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_service_slug_dacaebc3_like ON public.api_service USING btree (slug varchar_pattern_ops);


--
-- Name: api_serviceadvantage_active_a7d0c085; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_serviceadvantage_active_a7d0c085 ON public.api_serviceadvantage USING btree (active);


--
-- Name: api_serviceadvantage_order_d906c5f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_serviceadvantage_order_d906c5f2 ON public.api_serviceadvantage USING btree ("order");


--
-- Name: api_servicefaq_active_545c9c89; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicefaq_active_545c9c89 ON public.api_servicefaq USING btree (active);


--
-- Name: api_servicefaq_order_8d7abff8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicefaq_order_8d7abff8 ON public.api_servicefaq USING btree ("order");


--
-- Name: api_servicefaq_service_id_6f1b00c9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicefaq_service_id_6f1b00c9 ON public.api_servicefaq USING btree (service_id);


--
-- Name: api_servicereview_approved_e13c345c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicereview_approved_e13c345c ON public.api_servicereview USING btree (approved);


--
-- Name: api_servicereview_display_on_page_ba16dc70; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicereview_display_on_page_ba16dc70 ON public.api_servicereview USING btree (display_on_page);


--
-- Name: api_servicereview_service_id_fd6545b3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicereview_service_id_fd6545b3 ON public.api_servicereview USING btree (service_id);


--
-- Name: api_servicereview_user_id_cc2bc5db; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_servicereview_user_id_cc2bc5db ON public.api_servicereview USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: api_agency api_agency_created_by_id_002c2d46_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_agency
    ADD CONSTRAINT api_agency_created_by_id_002c2d46_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_contact api_contact_agency_id_d7d4ae04_fk_api_agency_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_contact
    ADD CONSTRAINT api_contact_agency_id_d7d4ae04_fk_api_agency_id FOREIGN KEY (agency_id) REFERENCES public.api_agency(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_contact api_contact_created_by_id_550e483b_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_contact
    ADD CONSTRAINT api_contact_created_by_id_550e483b_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_customuser api_customuser_created_by_id_fbaeaeef_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser
    ADD CONSTRAINT api_customuser_created_by_id_fbaeaeef_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_customuser_groups api_customuser_group_customuser_id_9eb4b783_fk_api_custo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_groups
    ADD CONSTRAINT api_customuser_group_customuser_id_9eb4b783_fk_api_custo FOREIGN KEY (customuser_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_customuser_groups api_customuser_groups_group_id_f049027c_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_groups
    ADD CONSTRAINT api_customuser_groups_group_id_f049027c_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_customuser_user_permissions api_customuser_user__customuser_id_5365c9ba_fk_api_custo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_user_permissions
    ADD CONSTRAINT api_customuser_user__customuser_id_5365c9ba_fk_api_custo FOREIGN KEY (customuser_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_customuser_user_permissions api_customuser_user__permission_id_8735d73e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_customuser_user_permissions
    ADD CONSTRAINT api_customuser_user__permission_id_8735d73e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_employeeprofile api_employeeprofile_user_id_d05b31af_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_employeeprofile
    ADD CONSTRAINT api_employeeprofile_user_id_d05b31af_fk_api_customuser_id FOREIGN KEY (user_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_invoice api_invoice_created_by_id_2da52342_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_invoice
    ADD CONSTRAINT api_invoice_created_by_id_2da52342_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_invoice api_invoice_quote_request_id_bf90dc5a_fk_api_quoterequest_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_invoice
    ADD CONSTRAINT api_invoice_quote_request_id_bf90dc5a_fk_api_quoterequest_id FOREIGN KEY (quote_request_id) REFERENCES public.api_quoterequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_pagecontent api_pagecontent_created_by_id_5091b166_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_pagecontent
    ADD CONSTRAINT api_pagecontent_created_by_id_5091b166_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_patient_assigned_employees api_patient_assigned_customuser_id_c3ba6567_fk_api_custo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient_assigned_employees
    ADD CONSTRAINT api_patient_assigned_customuser_id_c3ba6567_fk_api_custo FOREIGN KEY (customuser_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_patient_assigned_employees api_patient_assigned_patient_id_d2b97ec2_fk_api_patie; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient_assigned_employees
    ADD CONSTRAINT api_patient_assigned_patient_id_d2b97ec2_fk_api_patie FOREIGN KEY (patient_id) REFERENCES public.api_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_patient api_patient_client_id_4b1d6178_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient
    ADD CONSTRAINT api_patient_client_id_4b1d6178_fk_api_customuser_id FOREIGN KEY (client_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_patient api_patient_created_by_id_57cbf8d3_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_patient
    ADD CONSTRAINT api_patient_created_by_id_57cbf8d3_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_presence api_presence_employe_id_1f76278e_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_presence
    ADD CONSTRAINT api_presence_employe_id_1f76278e_fk_api_customuser_id FOREIGN KEY (employe_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_presence api_presence_patient_id_fe27ba5c_fk_api_patient_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_presence
    ADD CONSTRAINT api_presence_patient_id_fe27ba5c_fk_api_patient_id FOREIGN KEY (patient_id) REFERENCES public.api_patient(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_quoteformoption api_quoteformoption_parent_id_2edec2f9_fk_api_quote; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoteformoption
    ADD CONSTRAINT api_quoteformoption_parent_id_2edec2f9_fk_api_quote FOREIGN KEY (parent_id) REFERENCES public.api_quoteformoption(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_quoteformoption api_quoteformoption_step_id_e088f7df_fk_api_quoteformstep_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoteformoption
    ADD CONSTRAINT api_quoteformoption_step_id_e088f7df_fk_api_quoteformstep_id FOREIGN KEY (step_id) REFERENCES public.api_quoteformstep(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_quoteformstep api_quoteformstep_service_id_9b80a884_fk_api_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoteformstep
    ADD CONSTRAINT api_quoteformstep_service_id_9b80a884_fk_api_service_id FOREIGN KEY (service_id) REFERENCES public.api_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_quoterequest api_quoterequest_created_by_user_id_d39b68c5_fk_api_custo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoterequest
    ADD CONSTRAINT api_quoterequest_created_by_user_id_d39b68c5_fk_api_custo FOREIGN KEY (created_by_user_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_quoterequest api_quoterequest_service_id_98f70f85_fk_api_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_quoterequest
    ADD CONSTRAINT api_quoterequest_service_id_98f70f85_fk_api_service_id FOREIGN KEY (service_id) REFERENCES public.api_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_service_agencies api_service_agencies_agency_id_893f471b_fk_api_agency_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service_agencies
    ADD CONSTRAINT api_service_agencies_agency_id_893f471b_fk_api_agency_id FOREIGN KEY (agency_id) REFERENCES public.api_agency(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_service_agencies api_service_agencies_service_id_2fc1f491_fk_api_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service_agencies
    ADD CONSTRAINT api_service_agencies_service_id_2fc1f491_fk_api_service_id FOREIGN KEY (service_id) REFERENCES public.api_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_service api_service_category_id_7dadc477_fk_api_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service
    ADD CONSTRAINT api_service_category_id_7dadc477_fk_api_category_id FOREIGN KEY (category_id) REFERENCES public.api_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_service api_service_created_by_id_0510348a_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_service
    ADD CONSTRAINT api_service_created_by_id_0510348a_fk_api_customuser_id FOREIGN KEY (created_by_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_servicefaq api_servicefaq_service_id_6f1b00c9_fk_api_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_servicefaq
    ADD CONSTRAINT api_servicefaq_service_id_6f1b00c9_fk_api_service_id FOREIGN KEY (service_id) REFERENCES public.api_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_servicereview api_servicereview_service_id_fd6545b3_fk_api_service_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_servicereview
    ADD CONSTRAINT api_servicereview_service_id_fd6545b3_fk_api_service_id FOREIGN KEY (service_id) REFERENCES public.api_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_servicereview api_servicereview_user_id_cc2bc5db_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_servicereview
    ADD CONSTRAINT api_servicereview_user_id_cc2bc5db_fk_api_customuser_id FOREIGN KEY (user_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_api_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_api_customuser_id FOREIGN KEY (user_id) REFERENCES public.api_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict MwzFg0gq1yReWnDI8qbnp1InCe6dLOhg4UuOXOpaa05h6qbogQsIN2iWxWM5iN1

